Vntrip.vn/Vntrip.vn/Controllers/khuVucController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vntrip.vn.Models;

namespace Vntrip.vn.Controllers
{
    public class khuVucController : Controller
    {
        vntripDataContext db = new vntripDataContext();
        // GET: khuVuc
        public ActionResult Index(int? page)
        {
            var khuVuc = from kv in db.KhuVucs select kv;
            return View(khuVuc.ToPagedList(page ?? 1,10));
        }
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(FormCollection collection, KhuVuc khuvuc)
        {
            // Tạo biến CB_Loaitin và gán giá trị của người dùng nhập vào từ
            //form trong trang Create.aspx
            var TenKhuVuckhuvuc = khuvuc.TenKhuVuc;
            //Nếu CB_Loaitin có giá trị == null ( để trống) 
            if (string.IsNullOrEmpty(TenKhuVuckhuvuc))
            {
                ViewData["error"] = " Tên khu vực không được để trống ";
            }
            else
            {
                khuvuc.TenKhuVuc = TenKhuVuckhuvuc;
                db.KhuVucs.InsertOnSubmit(khuvuc);
                //Thực hiện tạo mới
                db.SubmitChanges();
                return RedirectToAction("Index");
            }
            return this.Create();
        }
        public ActionResult Edit(int id)
        {
            var kv = db.KhuVucs.First(m => m.ID == id);
            return View(kv);
        }

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection, KhuVuc khuvuc)
        {
            // Tạo một biến Ltin gán với đối tượng có id=id truyền vào
            //var Ltin = data.Theloaitins.First(m => m.IDLoai == id);
            var kv = db.KhuVucs.First(m => m.ID == id);
            //var E_Loaitin = collection["TenKhuVuctheloai"];
            var TenKhuVuckhuvuc = khuvuc.TenKhuVuc;
            //vì ta sửa đối tượng lên Id của biến Ltin = Id chuyền vào .
            kv.ID = id;
            // Nếu người dùng để phần Loại Tin trống báo lỗi
            if (string.IsNullOrEmpty(TenKhuVuckhuvuc))
            {
                ViewData["Loi"] = " Tên khu vực không được để trống ";
            }
            // Ngược lại gán các trường của biến Ltin bằng các giá trị 
            //của người dùng nhập vào
            else
            {
                kv.TenKhuVuc = TenKhuVuckhuvuc;
                // Thực hiện updat
                UpdateModel(kv);
                db.SubmitChanges();
                return RedirectToAction("Index");
            }
            return this.Edit(id);
        }
        public ActionResult Delete(int id)
        {
            var kv = db.KhuVucs.First(m => m.ID == id);
            return View(kv);
        }

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection, KhuVuc khuvuc)
        {
            // Tạo biến D_Tin gán với dối dượng có ID bằng với ID tham số
            var kv = db.KhuVucs.Where(m => m.ID == id).First();
            //xóa
            db.KhuVucs.DeleteOnSubmit(kv);
            db.SubmitChanges();
            return RedirectToAction("Index");
        }
    }
}

Vntrip.vn/Vntrip.vn/Views/khuVuc/Create.cshtml
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Share/_Admin.cshtml";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
                    <li class="breadcrumb-item active">Form thêm khu vực</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<div class="card-body pad">
    <div class="row">
        <div class="col-md-12">
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Form thêm khu vực</h3>
                </div>
                <font color=red>
                    @ViewData["error"]
                </font>
                <form role="form" method="POST" action="/khuVuc/Create"
                      enctype="multipart/form-data">
                    <div class="card-body">
                        <div class="form-group">
                            <label for="product_name">Tên khu vực</label>
                            <input type="text" class="form-control" placeholder="Điền tên khu vực"
                                   name="Ten" id="Ten">
                        </div>
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Thêm</button>
                    </div>
                </form>
            </div>
            <!-- /.card -->
        </div>
    </div>
</div>

Vntrip.vn/Vntrip.vn/Views/khuVuc/Delete.cshtml
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Share/_Admin.cshtml";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
                    <li class="breadcrumb-item active">Form xóa khu vực</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<div class="card-body pad">
    <div class="row">
        <div class="col-md-12">
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Form xóa khu vực</h3>
                </div>
                <form role="form" method="POST" action="/khuVuc/Delete/@Model.ID"
                      enctype="multipart/form-data">
                    <div class="card-body">
                        <div class="form-group">
                            <label for="product_name">ID</label>
                            <input type="text" class="form-control"
                                   name="ID" id="ID" value="@Model.ID">
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            <label for="product_name">Tên khu vực</label>
                            <input type="text" class="form-control"
                                   name="Ten" id="Ten" value="@Model.Ten">
                        </div>
                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Xóa</button>
                    </div>
                </form>
            </div>
            <!-- /.card -->
        </div>
    </div>
</div>

Vntrip.vn/Vntrip.vn/Views/khuVuc/Edit.cshtml
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Share/_Admin.cshtml";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
                    <li class="breadcrumb-item active">Form sửa khu vực</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<div class="card-body pad">
    <div class="row">
        <div class="col-md-12">
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Form sửa khu vực</h3>
                </div>
                <font color=red>
                    @ViewData["Loi"]
                </font>
                <form role="form" method="POST" action="/khuVuc/Edit/@Model.ID"
                      enctype="multipart/form-data">
                    <div class="card-body">
                        <div class="form-group">
                            <label for="product_name">Tên khu vực</label>
                            <input type="text" class="form-control" placeholder="Điền tên khu vực"
                                   name="Ten" id="Ten" value="@Model.Ten">
                        </div>
                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Sửa</button>
                    </div>
                </form>
            </div>
            <!-- /.card -->
        </div>
    </div>
</div>

Vntrip.vn/Vntrip.vn/Views/khuVuc/Index.cshtml
@model IPagedList<Vntrip.vn.Models.KhuVuc>

@using PagedList.Mvc;
@using PagedList;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Share/_Admin.cshtml";
}
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Khu vực</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
                    <li class="breadcrumb-item active">Khu vực</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<form class="form-inline ml-3" method="get" action="">
    <div class="container h-100">
        <div class="d-flex justify-content-center h-100">
            <div class="searchbar">
                <input class="search_input" type="text" name="key" placeholder="Tìm kiếm">
                <a href="" class="search_icon"><i class="fas fa-search"></i></a>
            </div>
        </div>
    </div>
</form>
<br>

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Bảng khu vực</h3>
                    </div>
                    <font color=green>
                        @ViewData["success"]
                    </font>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                                <tr align="center">
                                    <th>ID</th>
                                    <th>Tên</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr class="odd gradeX" align="center">
                                        <td>@item.ID</td>
                                        <td>@item.TenKhuVuc</td>
                                        <td>
                                            <i class="fa fa-trash-o" fa-fw></i>@Html.ActionLink("Sửa", "Edit", new { id = item.ID })
                                            <i class="fa fa-pencil fa-fw"></i>@Html.ActionLink("Xóa", "Delete", new { id = item.ID })
                                        </td>
                                    </tr>
                                }
                            </tbody>
                            <tfoot>
                                <tr align="center">
                                    <th>ID</th>
                                    <th>Tên</th>
                                    <th>Action</th>
                                </tr>
                            </tfoot>
                        </table>
                        <div style="margin-left:0px" class="paginate">
                            @Html.PagedListPager(Model, page => Url.Action("Index", "khuVuc", new { page }))
                        </div>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->

            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</section>
<!-- /.content -->